### ISSUE TITLE
Добавить маленькое ридми

### ISSUE THREAD

**Issue by khorevaa** [djserega/ComparisonAssistant#1]
Прошу добавить маленькое ридми что бы понимать, зачем это? 

пс просто интересно ) А может и даже полезно будет )

**Comment by djserega** [comment]
Спасибо за интерес :)

Я планировал на этой неделе как раз заняться маленькой инструкцией к программке.

В двух словах: Парсим выгруженные по определенному формату логи git'а.

В итоге получаем:
- фильтры:
Пользователь, Имя задачи, Дата помещения в хранилище.
- таблицу: 
Тип помещения, Объект изменения (добавлен реквизит, изменен модуль...)

**Comment by djserega** [comment]
Добавил маленькое ридми 😃
